"""migracao

Revision ID: 7647599f281a
Revises: 
Create Date: 2026-08-03 19:59:00.848244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7647599f281a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nome', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('Telefone', sa.Integer(), nullable=True),
    sa.Column('Senha', sa.String(), nullable=True),
    sa.Column('Admin', sa.Boolean(), nullable=True),
    sa.Column('Endereco', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
