"""adicionar itens no pedido

Revision ID: e5ad4f2c876a
Revises: 9cdee1ea56a7
Create Date: 2026-06-15 08:33:26.608733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5ad4f2c876a'
down_revision: Union[str, Sequence[str], None] = '9cdee1ea56a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
